<?php

namespace AppBundle\Repository;

/**
 * BillPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
