<?php

namespace AppBundle\Repository;

/**
 * BillTypePlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillPlanTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
