<?php

namespace AppBundle\Repository;

/**
 * BillInstallmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillInstallmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
