<?php

namespace AppBundle\Repository;

/**
 * BillStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
