<?php

namespace AppBundle\Repository;

/**
 * BillCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryLatestForm()
    {
        return $this->createQueryBuilder('billCategory')
            ->orderBy('billCategory.description', 'ASC');
    }
}
