<?php

namespace AppBundle\Repository;

use AppBundle\Helper\PaginationHelper;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * BillPlanCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillPlanCategoryRepository extends AbstractEntityRepository
{
    protected function queryLatest(PaginationHelper $paginationHelper)
    {
        $routeParams = $paginationHelper->getRouteParams();

        $qb = $this->createQueryBuilder('billPlanCategory')
            ->innerJoin('billPlanCategory.billCategory', 'billCategory')
            ->addSelect('billCategory');

        if (isset($routeParams['search'])) {
            $qb->andWhere('billPlanCategory.description LIKE :search')->setParameter('search', '%' . $routeParams['search'] . '%');
        }

        if (!isset($routeParams['sorting'])) {
            $qb->orderBy('billPlanCategory.id', 'desc');
        } else {
            $qb = $this->addOrderingQueryBuilder($qb, $paginationHelper);
        }
        return $qb->getQuery();
    }

    public function findLatest(PaginationHelper $paginationHelper)
    {
        $routeParams = $paginationHelper->getRouteParams();

        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryLatest($paginationHelper), false));

        $paginator->setMaxPerPage($routeParams['num_items']);
        $paginator->setCurrentPage($routeParams['page']);

        return $paginator;
    }

    public function queryLatestForm()
    {
        return $this->createQueryBuilder('billPlanCategory')
            ->orderBy('billPlanCategory.description', 'ASC');
    }
}
