<?php

namespace AppBundle\Repository;

/**
 * BillInstallmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillInstallmentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByBills($bills)
    {
        $keys = array_keys($bills);

        $sqlBills = '';

        foreach ($keys as $key) {
            $sqlBills .= $key . (next($keys) ? ',' : '');
        }

        $qb = $this->createQueryBuilder('billInstallments')
            ->addSelect()
            ->innerJoin('billInstallments.bill', 'bill')
            ->addSelect('bill')
            ->where('bill.id in ('.$sqlBills.')')
            ->orderBy('billInstallments.dueDateAt', 'asc');

        return $qb->getQuery()->getResult();
    }
}
