<?php

namespace AppBundle\Repository;

/**
 * BillFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillFilesRepository extends \Doctrine\ORM\EntityRepository
{
}
