# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_SYSTEM_CONTENT: [ROLE_USER]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory_system:
            memory:
                users:
                    '%system_user%':
                        password: '%system_pass%'
                        roles: [ROLE_SYSTEM_CONTENT]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        system:
            pattern:  ^/
            provider: in_memory_system
            form_login:
                provider: in_memory_system
                login_path: system_security_login
                check_path: system_security_login_check
                failure_path: system_security_login
                default_target_path: index
                username_parameter: login[login]
                password_parameter: login[password]
                use_forward: false
                use_referer: true
            remember_me:
                secret: "%secret%"
                path: /
                name: APP_SYSTEM_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: login[_remember_me]
            logout:
                path: system_security_logout
                target: system_security_login
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }